version: '3.3'

services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: app_db
    ports:
      - 5432:5432
    
  redis:
    image: redis:3.2
    ports:
      - 6379:6379

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/app_db
    ports:
      - 8000:8000
    volumes:
      - ./:/app